---
- hosts: all 
  become: true 
  vars:
    username: Alain 
    password:  Class25@2024
  tasks:
  - name: create users 
    user: 
      name: "{{username}}"
      password: "{{password}}"
      state:  present
    with_items:
      - {'username':'ivo', 'password':'liontech1990'}
      - {'username':'jack', 'password':'jack123!@#'}